import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.scss';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App meta data',
    description: 'Generated by create next app',
};
import { ApolloWrapper } from './ApolloWrapper';
import { Header } from '@components/layout/header/Header';
import { Footer } from '@components/layout/footer/Footer';
import { MainInterior } from '@components/layout/main/MainInterior';
import { ReactNode } from 'react';

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
                />
                <title>ok</title>
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ApolloWrapper>
                    <Header />
                    <MainInterior>{children}</MainInterior>

                    <Footer />
                </ApolloWrapper>
            </body>
        </html>
    );
}
